### ISSUE TITLE
Unexpected feature "Person=Impers"

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_Welsh-CCG#6]
In the 2.4 release, there are 84 occurrences of the feature `Person=Impers` (see: [Grew-match](http://match.grew.fr/?corpus=UD_Welsh-CCG@2.4&custom=5cdfef69cef8b)). According to https://universaldependencies.org/u/feat/Person.html, the feature should be `Person=0`, isn't it?

**Comment by ftyers** [comment]
@bguil yes, it appears that it should be `Person=0`, in the Breton treebank this is `Person=Auto` which should also be changed.

**Comment by jheinecke** [comment]
I totally agree, it has been corrected on dev-branch
